FROM python:buster

ENV IMAP_SERVER=IMAP_SERVER
ENV SMTP_SERVER=SMTP_SERVER
ENV DETECTIVE_MAIL=DETECTIVE_MAIL
ENV DETECTIVE_LOGIN=DETECTIVE_LOGIN
ENV DETECTIVE_PASSWORD=DETECTIVE_PASSWORD

WORKDIR /usr/src/app

COPY . .

RUN pip3 install -r  requirements.txt

ENTRYPOINT ["python3"]
CMD ["main.py"]